import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeeef",
        "error": "#ba1a1a",
        "primary-fixed": "#d8e2ff",
        "primary-container": "#2170e4",
        "surface-variant": "#e1e3e4",
        "surface-bright": "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fefcff",
        "on-secondary-container": "#00714d",
        "secondary-fixed": "#6ffbbe",
        "tertiary-container": "#b75b00",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary": "#006c49",
        "tertiary-fixed": "#ffdcc6",
        "inverse-primary": "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "on-background": "#191c1d",
        "outline-variant": "#c2c6d6",
        "surface-dim": "#d9dadb",
        "secondary-fixed-dim": "#4edea3",
        "on-surface-variant": "#424754",
        "surface": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#924700",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary": "#0058be",
        "surface-tint": "#005ac2",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#004395",
        "secondary-container": "#6cf8bb",
        "background": "#f8f9fa",
        "outline": "#727785",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#311400",
        "on-primary-fixed": "#001a42",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed-dim": "#ffb786",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#002113",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
    },
  },
  plugins: [],
};

export default config;
